version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp
commands:
  boss_greeting:
    description: "I am trying to try command to reuse some of my code"    
    parameters:
      name:
        defaut: "toan"
        type: string
      age:
        default: 30
        type: integer
    stepds:
      - run: echo "Hello <<parameters.name>>. You are <<parameters.age>> rights?"
jobs:
  writting:
    executor: my-executor
    steps:
      - boss_greeting:
          name: "Toan"
          age: 30
      - run: mkdir -p workspace
      - run: echo "Hi Toan, you are being father :)" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  reading:
    executor: my-executor
    steps:
      - boss_greeting:
          name: "Ngan"
          age: 25    
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/echo-output
workflows:
  say-hello-workflow:
    jobs:
      - writting
      - reading:
          requires:
          - writting
