# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp
jobs:
  writting:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - run: echo "Hi Toan, you are being father :)" > workspace/$CIRCLE_BUILD_NUM
      - persist_to_workspace:
          root: workspace
          paths:
            - $CIRCLE_BUILD_NUM
  reading:
    executor: my-executor
    steps:
    - attach_workspace:
          at: /tmp/workspace
      run: cat /tmpworkspace/$CIRCLE_BUILD_NUM
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - writting
      - reading:
        requires:
          - writting
