version: 2.1
executors:
  aws-executor:
    docker:
      - image: amazon/aws-cli
  my-executor:
    docker:
      - image: python:3.8
commands:
  boss-greeting:
    description: "I am trying to try command to reuse some of my code"    
    parameters:
      first-name:
        default: "toan"
        type: string
      age:
        default: 30
        type: integer
    steps:
      - run: echo "Hello <<parameters.first-name>>. You are <<parameters.age>> rights?"
  install-dependencies:
    description: "Install some of necessary dependency for amazon/aws-cli image"
    steps:
      - run: yum install -y jq
      - run: yum install -y tar
      - run: yum install -y gzip


  destroy_environment:
    description: "Delete created infrastructure if fail to ping"
    steps:
      - run:
          name: "Delete infrastructure"
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
jobs:
  writting:
    executor: my-executor
    steps:
      - boss-greeting:
          first-name: "Toan"
          age: 30
      - run: mkdir -p workspace
      - run: echo "Hi Toan, you are being father :)" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  reading:
    executor: my-executor
    steps:
      - boss-greeting:
          first-name: "Ngan"
          age: 25    
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/echo-output
  misc:
    executor: my-executor
    steps:
      - run: |
          if [[ 'cat /tmp/workspace/echo-output' == "some testing code" ]]; then
            echo "contents is expected";
          else
            echo "contents is something else"; exit 0
          fi
      - run:
          name: shout out on some failure
          command: echo "Hi Toan, now you see how on_fail works right?"
          when: on_fail
  create_infrastructure:
    executor: aws-executor
    steps:
      - checkout
      - install-dependencies
      - run: | 
          aws cloudformation deploy --template-file create-ec2-template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
      - run: mkdir -p /tmp/cicd-workspace
      - run: |
          stack_status="CREATE_IN_PROGRESS"
          while [ "$stack_status" != "CREATE_COMPLETE" ]; do
            stack_status=$(aws cloudformation describe-stacks --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} | jq -r '.Stacks[0].StackStatus')
            if [ "$stack_status" == "ROLLBACK_COMPLETE" ]; then
              echo "CloudFormation stack creation failed."
              exit 1
            fi
            sleep 5
          done
          echo "CREATE_COMPLETE" > /tmp/cicd-workspace/output.txt
      - persist_to_workspace:
          root: /tmp/cicd-workspace
          paths:
            - output.txt
  configure_infrastructure:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["ee:47:ec:7f:49:b2:c8:0e:73:71:79:6e:bc:98:85:c6"]
      - run:
          name: Install Ansible
          command: | 
            pip install ansible
      - run:
          name: Run play book and configure server
          command: | 
            ansible-playbook -i inventory main.yml
  smoke-test:
    executor: aws-executor
    steps:
      - checkout
      - install-dependencies
      - attach_workspace:
          at: /tmp/cicd-workspace
          paths:
            - output.txt
      - run: |
          if [[ $(cat /tmp/cicd-workspace/output.txt) == "CREATE_COMPLETE" ]]; then
            echo "Infrastructure created successfully";
          else
            cat /tmp/cicd-workspace/output.txt 
            echo "Infrastructure was not created"; exit 1
          fi      
      - destroy_environment
  create_and_deploy_front_end:
    executor: aws-executor
    steps:
      - checkout
      - run:
          name: Execute cloud formation to create S3 Bucket
          command: |
            aws cloudformation deploy \
            --template-file create-s3bucket-template.yml \
            --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:5} \
            --parameter-overrides MyBucketName="cicd-bucket-${CIRCLE_WORKFLOW_ID:0:5}"
      - run: aws s3 sync . s3://cicd-bucket-${CIRCLE_WORKFLOW_ID:0:5} --delete
  get_last_deployment_id:
    executor: aws-executor
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Fetch and save the old pipeline ID (bucket name) responsible for the last release.
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > ~/textfile.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - textfile.txt      
  promote_to_production:
    executor: aws-executor
    steps:
      - checkout
      - run:
          name: Execute create-cloudfront-template.yml
          command: |
            aws cloudformation deploy \
            --template-file create-cloudfront-template.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="mybucket-${CIRCLE_WORKFLOW_ID:0:5}"
  clean_up_old_front_end:
    executor: aws-executor
    steps:
      - checkout
      - install-dependencies
      - attach_workspace:
          at: ~/
      - run:
          name: Destroy the previous S3 bucket and CloudFormation stack. 
          # Use $OldBucketID environment variable or mybucket644752792305 below.
          # Similarly, you can create and use $OldStackID environment variable in place of production-distro 
          command: |
            export OldBucketID=$(cat ~/textfile.txt)
            aws s3 rm "s3://${OldBucketID}" --recursive

workflows:
  create_deploy_frontend:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
          requires: 
            - create_and_deploy_front_end
      - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - get_last_deployment_id
            - promote_to_production 

#  create-infra:
#    jobs:
#      - create_infrastructure
#      - smoke-test:
#          requires:
#          - create_infrastructure

#  install-ansible-start-server:
#    jobs:
#      - configure_infrastructure
#      - writting
#      - reading:
#          requires:
#          - writting
#      - misc
