version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp
jobs:
  writting:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - run: echo "Hi Toan, you are being father :)" > workspace/output
      - persist_to_workspace:
          root: workspace
          paths:
            - output
  reading:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmpworkspace/output
workflows:
  say-hello-workflow:
    jobs:
      - writting
      - reading:
        requires:
          - writting
