version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp
commands:
  boss-greeting:
    description: "I am trying to try command to reuse some of my code"    
    parameters:
      first-name:
        default: "toan"
        type: string
      age:
        default: 30
        type: integer
    steps:
      - run: echo "Hello <<parameters.first-name>>. You are <<parameters.age>> rights?"
jobs:
  writting:
    executor: my-executor
    steps:
      - boss-greeting:
          first-name: "Toan"
          age: 30
      - run: mkdir -p workspace
      - run: echo "Hi Toan, you are being father :)" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  reading:
    executor: my-executor
    steps:
      - boss-greeting:
          first-name: "Ngan"
          age: 25    
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/echo-output
  misc:
    executor: my-executor
    steps:
      - run: |
          if [[ 'cat /tmp/workspace/echo-output' == "some testing code" ]]; then
            echo "contents is expected";
          else
            echo "contents is something else"; exit 0
          fi
      - run:
          name: shout out on some failure
          command: echo "Hi Toan, now you see how on_fail works right?"
          when: on_fail
  create_infrastructure:
    docker:
      - image: amazon/aws-cli 
    steps:
      - checkout
      - run: | 
          aws cloudformation deploy \ 
          --template-file template.yml \ 
          --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \ 
          --region us-east-1
workflows:
  say-hello-workflow:
    jobs:
      - create_infrastructure
#      - writting
#      - reading:
#          requires:
#          - writting
#      - misc
