---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  become: yes

- name: Install npm
  apt:
    name: npm
    state: present
  become: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
#- name: Install Apache web server
#  apt:
#    name: apache2
#    state: present

- name: Create ~/web directory if it doesn't exist
  file:
    path: ~/web
    state: directory
#    mode: '0755'

- name: Copy file from 
  copy:
    src: files/index.js
    dest: ~/web/index.js
#    mode: '0644'

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f
#- name: Start Apache web server
#  service:
#    name: apache2
#    state: started
#    enabled: yes